#logging.level.root: DEBUG

server.port: 9000

blockchainspace:
  jwt:
    secret: BlockchainSpace
    expiration: 1800 # in seconds, for example
  cache.redis:
    host: localhost
    port: 6379
    ttl: 1800 # in seconds

spring:
  datasource:
    url: jdbc:h2:mem:blockchainspace
    username: h2
    password: h2pass
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2