server.port: 9000

jwt.secret: BlockchainSpace

spring:
  datasource:
    url: jdbc:h2:mem:blockchainspace
    username: h2
    password: h2pass
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect