server.port: 9000

blockchainspace.jwt:
  secret: BlockchainSpace
  expiration: 30 # in seconds, for example

spring:
  datasource:
    url: jdbc:h2:mem:blockchainspace
    username: h2
    password: h2pass
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect